DEFINES+=DISABLE_JSON
DEFINES+=DISABLE_RTC
DEFINES+=DISABLE_FS
DEFINES+=DISABLE_PRINTF_FLOAT

DEFINES+=ENABLE_TFTP_SERVER
DEFINES+=CONFIG_REMOTECONFIG_MINIMUM

DEFINES+=UDP_MAX_PORTS_ALLOWED=3
DEFINES+=ENET_RXBUF_NUM=2 ENET_TXBUF_NUM=2

DEFINES+=RTL8201F_LED1_LINK_ALL

SRCDIR+=firmware lib

LIBS+=remoteconfig flashcodeinstall configstore display flashcode flash
